### ISSUE TITLE
 ERROR: Dependency "gobject-introspection-1.0" not found, tried pkgconfig and cmake

### ISSUE THREAD

**Issue by eeriemyxi** [gnome-pomodoro/gnome-pomodoro#670]
I am using an Arch-based distribution, Crystal Linux. Pacman shows that I have already installed the necessary packages:
```yaml
crystal :: ~/Downloads/gnome-pomodoro ‹gnome-44› » pacman -Si gobject-introspection                                                    1 ↵
Repository      : extra
Name            : gobject-introspection
Version         : 1.78.1-1
Description     : Introspection system for GObject-based libraries
Architecture    : x86_64
URL             : https://wiki.gnome.org/Projects/GObjectIntrospection
Licenses        : GPL  LGPL
Groups          : None
Provides        : None
Depends On      : gobject-introspection-runtime=1.78.1-1  python-mako  python-markdown
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 1288.26 KiB
Installed Size  : 13533.99 KiB
Packager        : Jan Alexander Steffens (heftig) <heftig@archlinux.org>
Build Date      : Sat 16 Sep 2023 08:21:23 PM IST
Validated By    : MD5 Sum  SHA-256 Sum  Signature

crystal :: ~/Downloads/gnome-pomodoro ‹gnome-44› » pacman -Si gobject-introspection-runtime
Repository      : extra
Name            : gobject-introspection-runtime
Version         : 1.78.1-1
Description     : Introspection system for GObject-based libraries - runtime
Architecture    : x86_64
URL             : https://wiki.gnome.org/Projects/GObjectIntrospection
Licenses        : GPL  LGPL
Groups          : None
Provides        : None
Depends On      : libgirepository=1.78.1-1
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 172.85 KiB
Installed Size  : 705.98 KiB
Packager        : Jan Alexander Steffens (heftig) <heftig@archlinux.org>
Build Date      : Sat 16 Sep 2023 08:21:23 PM IST
Validated By    : MD5 Sum  SHA-256 Sum  Signature
```
[A forum answer](https://stackoverflow.com/a/66065656) suggests that having installed the package `gobject-introspection` should have resolved the issue, however in my case, it seems it did not...

When I try to build the package from source, it cannot find `gobject-introspection-1.0`.
```yaml
crystal :: ~/Downloads/gnome-pomodoro ‹gnome-44› » meson . build --prefix=/usr
meson compile -C build
sudo meson install -C build --no-rebuild
The Meson build system
Version: 1.2.1
Source dir: /home/eeriemyxi/Downloads/gnome-pomodoro
Build dir: /home/eeriemyxi/Downloads/gnome-pomodoro/build
Build type: native build
Project name: gnome-pomodoro
Project version: 0.23.0
C compiler for the host machine: cc (gcc 13.2.1 "cc (GCC) 13.2.1 20230801")
C linker for the host machine: cc ld.bfd 2.41.0
Vala compiler for the host machine: valac (valac 0.56.13)
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (1.8.1)
Run-time dependency glib-2.0 found: YES 2.76.4
Run-time dependency gobject-2.0 found: YES 2.76.4
Run-time dependency gio-2.0 found: YES 2.76.4
Run-time dependency gtk+-3.0 found: YES 3.24.38
Run-time dependency gdk-pixbuf-2.0 found: YES 2.42.10
Run-time dependency cairo found: YES 1.17.8
Found CMake: /usr/bin/cmake (3.27.4)
WARNING: CMake Toolchain: Failed to determine CMake compilers state
Run-time dependency gobject-introspection-1.0 found: NO (tried pkgconfig and cmake)

meson.build:17:20: ERROR: Dependency "gobject-introspection-1.0" not found, tried pkgconfig and cmake

A full log can be found at /home/eeriemyxi/Downloads/gnome-pomodoro/build/meson-logs/meson-log.txt
```

**Comment by kamilprusko** [comment]
I'm not an expert in arch, but it looks like you also need [libgirepository](https://archlinux.org/packages/extra/x86_64/libgirepository/) which provides a file `usr/lib/pkgconfig/gobject-introspection-1.0.pc`.

libgirepository is supposed to be a dependency of [gobject-introspection-runtime](https://archlinux.org/packages/extra/x86_64/gobject-introspection-runtime/)... Not sure why it's missing.

**Comment by eeriemyxi** [comment]
This was already installed as well. I've tried reinstalling, it didn't do it.

```yaml
crystal :: ~/Downloads/gnome-pomodoro ‹gnome-44› » pacman -Si libgirepository                                                          1 ↵
Repository      : extra
Name            : libgirepository
Version         : 1.78.1-1
Description     : Introspection system for GObject-based libraries - runtime library
Architecture    : x86_64
URL             : https://wiki.gnome.org/Projects/GObjectIntrospection
Licenses        : GPL  LGPL
Groups          : None
Provides        : libgirepository-1.0.so=1-64
Depends On      : libffi.so=8-64  libglib-2.0.so=0-64  libgobject-2.0.so=0-64  libgmodule-2.0.so=0-64  libgio-2.0.so=0-64
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 148.55 KiB
Installed Size  : 1591.25 KiB
Packager        : Jan Alexander Steffens (heftig) <heftig@archlinux.org>
Build Date      : Sat 16 Sep 2023 08:21:23 PM IST
Validated By    : MD5 Sum  SHA-256 Sum  Signature
```
